:book: Add vappconfig.md doc
vmware-tanzu/vm-operator pull request #175
Opened 2023-07-07 22:51 UTC by zyiyi11

**What does this PR do, and why is it needed?**
Add doc for vAppConfig bootstrap. 

**Which issue(s) is/are addressed by this PR?** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:

Fixes #123

2023-07-10 16:28 UTC, srm09 requested changes
Minor nits, and checkout the preview page generated. Was very helpful to me when reviewing
https://vm-operator--175.org.readthedocs.build/en/175/tutorials/deploy-vm/vappconfig/#supporting-template-queries

2023-07-10 16:28 UTC, srm09 commented on docs/tutorials/deploy-vm/vappconfig.md
> +As a DevOp, you can assign Golang-based template strings to vAppConfig values to send information into the guest that is not known ahead of time, such as the IPAM data settings used to configure the
```suggestion
As a DevOps user, you can assign Golang-based template strings to vAppConfig values to send information into the guest that is not known ahead of time, such as the IPAM data settings used to configure the VM's network stack.
```

2023-07-10 16:28 UTC, srm09 commented on docs/tutorials/deploy-vm/vappconfig.md
> +1.  :wave: The Golang based template string is a representation of [vm-operator virtualmachinetempl_types v1alpha1 api](https://github.com/vmware-tanzu/vm-operator/blob/25fb865e615d377192a870583ab329
Also for the bullets to appear on separate lines, you will need to add a blank line between the two.

2023-07-10 16:28 UTC, srm09 commented on docs/tutorials/deploy-vm/vappconfig.md
> +```
```suggestion
```yaml
```
☝🏾 For syntax highlighting

2023-07-10 16:28 UTC, srm09 commented on docs/tutorials/deploy-vm/vappconfig.md
> +```
```suggestion
```xml
```

2023-07-10 22:46 UTC, srm09 commented on docs/tutorials/deploy-vm/vappconfig.md
> +As a DevOp user, you can assign Golang-based template strings to vAppConfig values to send information into the guest that is not known ahead of time, such as the IPAM data settings used to configure
```suggestion
As a DevOps user, you can assign Golang-based template strings to vAppConfig values to send information into the guest that is not known ahead of time, such as the IPAM data settings used to configure the VM's network stack.
```

2023-07-10 22:47 UTC, srm09 requested changes
one final nit, before LGTM

2023-07-12 03:04 UTC, dilyar85 approved these changes
LGTM with some minor suggestions added.

2023-07-12 19:02 UTC, zyiyi11 commented on docs/tutorials/deploy-vm/vappconfig.md
> +## Supporting Template Queries
What do you think if from Guest customization page we link vAppConfig section to this `vappconfig.md`? same goes to cloudinit, sysprep in the future. So in Guest customization page, we don't go into details on how to deploy but focus on the high level summary?

2023-07-12 20:32 UTC, srm09 commented
@dilyar85 had a comment but otherwise lgtm, approving.

2023-07-12 20:34 UTC, srm09 approved these changes

2023-07-12 21:32 UTC, zyiyi11 commented on docs/tutorials/deploy-vm/vappconfig.md
> +### Examples:
Sounds good. I added a vAppConfig with templating queries and also kept this part.

2023-07-13 02:14 UTC, dilyar85 commented on docs/tutorials/deploy-vm/vappconfig.md
> +## Supporting Template Queries
Yep, that sounds good to me too.

2023-07-13 22:26 UTC, merged