Add proxy address in web-console request
vmware-tanzu/vm-operator pull request #61
Opened 2023-02-16 11:31 UTC by dilyar85

This patch adds a new field to the WebConsoleRequest CR to store the proxy address that can be used to access the VM's web-console. It updates the `webconsolerequest_controller` to retrieve the proxy address info from the defined proxy service object (`kube-system/kube-apiserver-lb-svc`).

Testing Done:
- Updated unit & integration tests to cover the newly added field in the CR
- Internal gce2e test **running**
- Manually applied the change to an internal testbed and verified the updated reconciliation result:
```
$ kubectl get svc -n kube-system kube-apiserver-lb-svc -o jsonpath='{.status.loadBalancer.ingress[*].ip}'
192.168.0.2%
$ kubectl get webconsolerequest -n sdiliyaer-test  -o jsonpath='{.items[*].status.proxyAddr}'
192.168.0.2%
```

2023-02-16 15:05 UTC, akutz requested changes

2023-02-17 00:57 UTC, aruneshpa approved these changes
LGTM.  I really like @akutz's comment about keeping the API generic and future-proof.

2023-02-17 01:10 UTC, dilyar85 commented on api/v1alpha1/webconsolerequest_types.go
> +	// ProxyAddr is the address of the proxy server that can be used to access the VM's web-console.
Thank you. I have updated this comment and generated files based on your suggestion above.

2023-02-17 01:18 UTC, akutz approved these changes
Lgtm!

2023-02-17 03:51 UTC, merged