✨ Use capabilities at start up time
vmware-tanzu/vm-operator pull request #690
Opened 2024-08-30 19:43 UTC by bryanv

**What does this PR do, and why is it needed?**

Initial our context Features with the current state of the capabilities.

**Which issue(s) is/are addressed by this PR?** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:

Fixes #

**Are there any special notes for your reviewer**:

**Please add a release note if necessary**:

```release-note
NONE
```

2024-09-06 20:34 UTC, yashdesai93 requested changes

2024-09-09 16:04 UTC, bryanv commented on main.go
> +	if defaultConfig.Features.SVAsyncUpgrade {
I believe I was told that the async upgrade gated the capabilities? Should the env-var checking for FSS_WCP_TKG_Multiple_CL & FSS_WCP_WORKLOAD_DOMAIN_ISOLATION just be entirely removed then?

2024-09-09 21:28 UTC, yashdesai93 commented on main.go
> +	if defaultConfig.Features.SVAsyncUpgrade {
There are 2 or so use cases for TKG service-based capabilities used to derive Supervisor Capabilities  (relevant to this discussion): multiple_cl and workload domain isolation.
1. For Multiple_CL, a short-term approach for enabling SV capabilities based on service capabilities was implemented to unblock the feature and only applies to this feature. details are here: https://confluence.eng.vmware.com/display/WCP/Enabling+Multiple+CL+Capability+based+on+TKG+Service+Capability 
ST is verifying this approach to enable the multiple CL FSS. Guarded by FSS_WCP_TKG_Multiple_CL.

2. With Async Supervisor, we are introducing the common Capabilities CR which was extended to support Service Capabilities. This is the long-term approach detailed https://confluence.eng.vmware.com/display/WCP/One+Pager%3A+Exposing+Capabilities+Offered+by+a+Supervisor 

This is guarded by the Async FSS;

The second approach will be used for both Multiple_Cl and Workload Domain Isolation, but we still need to support the first approach before the second FSS gets enabled.


so in terms of this change:
1. if FSS_WCP_TKG_Multiple_CL is enabled, use capabilities to override only this FSS
2. if Async FSS is enabled, use capabilities to override both FSSs

2024-09-10 18:52 UTC, zyiyi11 approved these changes

2024-09-10 20:11 UTC, merged