:sparkles: Add ValidatingWebhookConfiguration controller
vmware-tanzu/vm-operator pull request #736
Opened 2024-10-07 19:08 UTC by abaruni

**What does this PR do, and why is it needed?**

Add ValidatingWebhookConfiguration controller to watch vm-operator's ValidatingWebhookConfiguration for changes and update the CA Bundle of any StoragePolicyUsage accordingly.

**Which issue(s) is/are addressed by this PR?** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:

Fixes #

**Are there any special notes for your reviewer**:

**Please add a release note if necessary**:

```release-note
Allow Storage Quota Extension Service to communicate with Storage Quota webhook
```

2024-10-07 23:03 UTC, sreyasn commented
Change looks good overall. Will look into the testing (unit/integ) files in a bit.

2024-10-08 20:39 UTC, akutz commented on controllers/virtualmachine/storagepolicyusage/webhookconfiguration/webhookconfiguration_controller.go
> +package webhookconfiguration
Please relocate this under `./controllers/infra/validatingwebhookconfiguration`.

2024-10-08 20:47 UTC, akutz commented on controllers/virtualmachine/storagepolicyusage/webhookconfiguration/webhookconfiguration_controller.go
> +				if err := r.Client.Update(ctx, &spu); err != nil {
`Update` should only be used in rare circumstances. Please use `Patch` instead. There is an example [here](https://github.com/vmware-tanzu/vm-operator/blob/39cdfbfab5f9174f1c56a04c0c9387f46d7823d1/controllers/virtualmachine/storagepolicyusage/storagepolicyusage_controller.go#L158-L172), although you will want to use the regular client, not the status client.

2024-10-08 20:49 UTC, akutz requested changes
Looks great @abaruni, just a few notes.

2024-10-08 20:49 UTC, sreyasn approved these changes
LGTM

2024-10-08 20:49 UTC, sreyasn commented on controllers/storagepolicyquota/storagepolicyquota_controller_unit_test.go
> +				Expect(err).To(HaveOccurred())
can we add another Expect() for substring match -- "unable to get CA bundle from secret" ?

2024-10-08 20:49 UTC, sreyasn commented on controllers/storagepolicyquota/storagepolicyquota_controller_intg_test.go
> +				g.Expect(obj.Spec.ResourceExtensionNamespace).To(Equal(ctx.PodNamespace))
can we also check if the fakeCABundle is present in Spec.CABundle here?.

2024-10-08 22:39 UTC, bryanv commented on controllers/infra/validatingwebhookconfiguration/validatingwebhookconfiguration_controller_unit_test.go
> +package validatingwebhookconfiguration_test
Missing boilerplate header

2024-10-08 23:56 UTC, abaruni commented on controllers/infra/validatingwebhookconfiguration/validatingwebhookconfiguration_controller_unit_test.go
> +package validatingwebhookconfiguration_test
thanks for catching

2024-10-09 16:48 UTC, akutz approved these changes
Thank you sir!

2024-10-09 16:49 UTC, merged